site_name: ECE5 TurtleBot Final Project 

nav:
  - Home: index.md
  - Team: team.md
  - Robot: robot.md
  - Proportional Integral Derivitave Controller: pid.md
  - Project Advice: advice.md

markdown_extensions:
  - pymdownx.arithmatex

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - javascripts/mathjax-config.js

